@baseUrl = http://localhost:3333
# @authToken = {{authenticate.response.body.access_token}}

# @name create_company
POST {{baseUrl}}/companies
Content-Type: application/json

{
  "name": "Teste Company LTDA",
  "tradeName": "Teste Company",
  "cnpj": "77.488.944/0001-84",
  "cnae": "112233",
  "ownerName": "Dono Teste",
  "ownerCpf": "03808164310",
  "phone": "85986744016",
  "ownerEmail": "teste@company.com",
  "password": "112233",
  "zipCode": "60181170",
  "uf": "CE",
  "city": "Fortaleza",
  "street": "Av. Areia Branca",
  "number": "524",
  "neighborhood": "Vicente Pinzon",
  "complement": "Casa"
}
