@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_company
POST {{baseUrl}}/companies
Content-Type: application/json

{
  "name": "Teste Company LTDA",
  "tradeName": "Teste Company",
  "cnpj": "77.488.944/0001-84",
  "cnae": "112233",
  "ownerName": "Dono Teste",
  "ownerCpf": "03808164310",
  "phone": "85986744016",
  "ownerEmail": "teste@company.com",
  "password": "112233",
  "zipCode": "60181170",
  "uf": "CE",
  "city": "Fortaleza",
  "street": "Av. Areia Branca",
  "number": "524",
  "neighborhood": "Vicente Pinzon",
  "complement": "Casa"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "teste@company.com",
  "password": "112233"
}

###

# @name create_document_type
POST {{baseUrl}}/document-types
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Teste 1",
  "fields": [
    { "name": "Data de vencimento", "type": "Date", "required": true }
  ]
}

###

# @name get_document_by_id
GET {{baseUrl}}/document-types/97ac517b-5abc-4339-bd56-d92ce731c599
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_document_types
GET {{baseUrl}}/document-types?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name change_document_type_active
PATCH {{baseUrl}}/document-types/32565b7a-3188-47fb-89f9-c19b31b1206f/active
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_document_type
DELETE {{baseUrl}}/document-types/77960c3b-4dad-4e81-8ef0-7bfcfa834a8b
Content-Type: application/json
Authorization: Bearer {{authToken}}
