services:
  # app:
  #   container_name: docsan-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - APP_PORT=${APP_PORT}
  #     - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
  #     - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
  #     - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  db:
    container_name: docsan-pg
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5442:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: docsan-redis
    image: redis:8
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  db-data:
  redis-data:
